routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Route for UI
 * TODO Delete if it becomes unnecessary
 */
Route::get('ui', function () {
    return (new \App\Helpers\SVGViewer\SvgViewer('s/images/useful/svg/theme/symbol-defs.svg'))->rengerSvg();
});

Route::get('lara-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('hack-test', function () {
    //$task = \App\UserTasks::find(469);

//    $deal = new \App\Services\WalletOneSafeDeal\WOSafeDeal();
////        $data = $deal::deal()->confirmDeal($task->deal->id);;
//
//    $data = $deal::payer()->getPayerRefunds($task->creator_id);
////    $data = $deal::deal()->cancelDeal($task->deal->id);;
////    $data = $deal::beneficiary()->getBeneficiaryPayouts($task->executor_id);
////    $data = $deal::deal()->completeDeal($task->deal->id);
//    dd($data);

    /*$task->update([
        'executor_id' => 0,
        'status' => 1,
        'executor_card_id' => null
    ]);
    \App\Review::whereTaskId($task->id)->forceDelete();
    \App\UserTaskDeal::query()->delete();*/

    dd("А хрен там! =)");


//    \App\User::find($task->creator_id)->notify(new \App\Notifications\PaymentStatusChanged($task, false));
});

//Route::get('test', function () {
////    $task = \App\UserTasks::find(request('task_id'));
//    $base_url = 'https://maps.googleapis.com/maps/api/geocode/json?';
//    $params = '&language=en&result_type=administrative_area_level_1';
//    $client = new \GuzzleHttp\Client();
////    $lat = $task->data['address'][0]['lat'] ?? false;
////    $lon = $task->data['address'][0]['lon'] ?? false;
//    $lat = '55.755826';
//    $lon = '37.617300';
//    if ($lat && $lon) {
//        $full_url = $base_url . 'latlng=' . $lat . ',' . $lon . '&key=' . config('services.google.maps_api_key').$params;
////        dd($full_url);
//        try {
//            $result =  json_decode_try($client->get($full_url)->getBody()->getContents());
//            $city = $result['results'][0]['address_components'][0]['long_name'];
//            if (strpos($city,' Oblast')) {
//                $city = stristr($city, ' Oblast', true);
//            }
//        }catch (Exception $e){
//            $city = \App\City::first()->name;
//        }
//    }
//    dd($city);
//    return '';
//    $safeDeal = new App\Services\WalletOneSafeDeal\WOSafeDeal();
//    return $safeDeal::deal()->getDeal('59113ed6-a95d-4e9b-a742-5c2ca20cad2f');
//    return $safeDeal::web()->payDeal([
//        "PlatformDealId" => 'c7769d6e-5233-11e8-9c2d-fa7ae01bbebc', // Идентификатор сделки на стороне площадки
//        "ReturnUrl" => 'http://pom.laraman.ru/payments', // Урл возврата пользователя
//    ]);
//});

Route::post('payments', 'Payment\SBRController@handleWalletOneRequest');


//Route::get('/', 'HomeController@index')->name('home');

Route::post('pay/in_request', 'Payment\ProcessorController@in_request')->name('in_request');

Route::group(['middleware' => ['web']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');

    Auth::routes();

    Route::post('/finish-register/prevalidate', 'Auth\RegisterController@ajaxValidate')->name('register_prevalidate');

    /*
     * Tasks group
     * */
    Route::group(['as' => 'task.', 'prefix' => 'task', 'namespace' => 'Tasks'], function () {
        Route::group(['middleware' => 'auth'], function () {
            Route::get('list', 'ListController@index')->name('list');
            Route::post('report/{id}', 'PreviewController@report')->name('report');
            Route::post('comment/{userTasks}', 'PreviewController@comment')->name('comment');
            Route::get('edit/{category}/{subcategory}/{userTasks}', 'EditController@index')->name('edit');
            Route::post('edit/{category}/{subcategory}/{userTasks}', 'EditController@edit')->name('edit');
            Route::post('field_edit/{userTasks}/{field}', 'EditController@field_edit')->name('edit.field');
            Route::post('/{task}/executor', 'EditController@selectExecutor')->name('edit.select-executor');
        });
        Route::post('store', 'NewController@storeOldData')->name('store.old');
        Route::get('all', 'ListController@all')->name('all');
        Route::get('sort', 'ListController@sort')->name('sort');
        Route::get('preview/{userTasks}', 'PreviewController@index')->name('review');

        Route::post('/{task}/review', 'ReviewsController@store')->name('review.store');
        Route::post('/{task}/offers', 'OffersController@store')->name('offers.store');
        Route::post('/offers/{offer}', 'OffersController@update')->name('offers.update');
        Route::delete('/offers/{offer}', 'OffersController@remove')->name('offers.remove');
        Route::get('/{task}/offers', 'PreviewController@getTaskReviews')->name('offers.sort');
        Route::get('new/{category}/{subcategory?}', 'NewController@index')->name('new');
        Route::get('copy/{userTasks}', 'NewController@copy_new')->name('copy');
        Route::post('create/{category}/{subcategory}', 'NewController@create')->name('create');
        Route::post('search', 'NewController@search')->name('search');
    });

    /*
     * Payment grout
     */

    Route::group(['as' => 'payment.', 'prefix' => 'payment', 'namespace' => 'Payment', 'middleware' => 'auth'], function () {
        Route::post('pay', 'ProcessorController@pay')->name('pay');
        Route::get('in/{hash}', 'ProcessorController@in')->name('in');
        Route::get('test', 'ProcessorController@test')->name('test');
        Route::get('cancel', 'ProcessorController@cancel')->name('cancel');
        Route::group(['as' => 'sbr.', 'prefix' => 'sbr'], function () {
            Route::get('index', 'SBRController@index')->name('index');
            Route::get('bind-payer-card', 'SBRController@bindPayerCard')->name('bind-payer-card');
            Route::match(['get', 'post'], 'handle-bind-payer-card', 'SBRController@handleBindPayerCard')->name('handle-bind-payer-card');
            Route::get('bind-beneficiary-card', 'SBRController@bindBeneficiaryCard')->name('bind-beneficiary-card');
            Route::match(['get', 'post'], 'handle-bind-beneficiary-card', 'SBRController@handleBindBeneficiaryCard')->name('handle-bind-beneficiary-card');
            Route::post('pay/{task}', 'SBRController@pay')->name('pay');
            Route::match(['get', 'post'], 'handle-pay', 'SBRController@handlePay')->name('handle-pay');
        });
    });

    Route::group(['as' => 'executors.', 'prefix' => 'executors'], function () {
        Route::get('/', 'ExecutorsController@index')->name('index');
        Route::get('/sort', 'ExecutorsController@sort')->name('sort');
        Route::post('/offer-job', 'ExecutorsController@offerJob')->name('offer-job');
    });

    Route::group(['prefix' => 'templates'], function () {
        Route::get('/list', 'API\TemplateController@index');
        Route::post('/store', 'API\TemplateController@store');
        Route::put('/{template}', 'API\TemplateController@update');
        Route::delete('/{template}', 'API\TemplateController@destroy');
    });

    Route::group(['prefix' => 'profile'], function () {
        Route::get('/{user}', 'ProfileController@show')->name('profile_show')->where('user', '[0-9]+');;
    });

    /*
     * Get Register user email (modal register)
     */
//    Route::middleware(['guest'])->group(function () {

    Route::post('/get/email/register', 'Auth\RegisterController@getEmail')->name('get_email');

    /*
    * Google
    */
    Route::get('/google/login', 'Auth\SocialLoginContoller@redirectToGoogleProvider')->name('social_google_auth');
    Route::get('/google/callback', 'Auth\SocialLoginContoller@handleGoogleProviderCallback')->name('social_google_callback');

    /*
     * Facebook
     */
    Route::get('/facebook/login', 'Auth\SocialLoginContoller@redirectToFacebookProvider')->name('social_facebook_auth');
    Route::get('/facebook/callback', 'Auth\SocialLoginContoller@handleFacebookProviderCallback')->name('social_facebook_callback');

    /*
     * Vkontakte
     */
    Route::get('/vk/login', 'Auth\SocialLoginContoller@redirectToVkProvider')->name('social_vk_auth');
    Route::get('/vk/callback', 'Auth\SocialLoginContoller@handleVkProviderCallback')->name('social_vk_callback');

    /*
     * Mail ru
     */
    Route::get('/mailru/login', 'Auth\SocialLoginContoller@redirectToMailProvider')->name('social_mailru_auth');
    Route::get('/mailru/callback', 'Auth\SocialLoginContoller@handleMailProviderCallback')->name('social_mailru_callback');
//    });

    /*
     * Congratulation
     */
    Route::get('/email/congratulation', 'Auth\RegisterController@congratulation')->name('congratulation');

    /*
     * Verification email
     */

    Route::get('/email/verification/{token}/{email}', 'Auth\RegisterController@checkToken')->name('email_verified');

    /*
     * Step 2 email register (After modal)
     */

    Route::get('/finish/registration', 'Auth\RegisterController@endRegister')->name('finish_register');

    Route::get('/finish/social/registration', 'Auth\SocialLoginContoller@endRegisterSocial')->name('finish_register_social');

    /*
     * Save data (step 2)
     */
    Route::post('create', 'ProfileController@postCreateProfile')->name('profile_create');


    /*
     * ????
     */
    Route::get('pick-email', 'Auth\LoginController@pickeEmail');
    Route::post('handle-email', 'Auth\LoginController@handleEmail');

    /*
     * Get JSON City
     */
    Route::group(['prefix' => 'location'], function () {

app/Http/Controllers/API/Tasks/CommentsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Uer
 * Date: 26.03.2018
 * Time: 16:30
 */

namespace App\Http\Controllers\API\Tasks;


use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Tasks\StoreOfferRequest;
use App\TaskComments;
use App\TaskOffers;
use App\UserTasks;
use Illuminate\Http\Request;

class CommentsController extends Controller
{

    public function store($task_id, Request $request)
    {
        $task = UserTasks::find($task_id);
        //&& TaskComments::store($task, $request->all())
        if ($task ) {
            $comments = $task->comments()->getSortedList();
            return response()->json($comments);
        }
        fail_message('Невозможно создать комментарий');
    }

    /**
     *
     * @param UserTasks $task
     * @param TaskComments $comment
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy(UserTasks $task, TaskComments $comment)
    {
        if ($comment->answer){
            TaskComments::destroy($comment->answer->id);
        }
        TaskComments::destroy($comment->id);
        $comments = $task->comments()->getSortedList();
        return response()->json($comments);
    }

}

app/Http/Controllers/API/Tasks/OffersController.php
<?php
/**
 * Created by PhpStorm.
 * User: Uer
 * Date: 26.03.2018
 * Time: 16:30
 */

namespace App\Http\Controllers\API\Tasks;


use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Tasks\StoreOfferRequest;
use App\TaskOffers;
use App\UserTasks;

class OffersController extends Controller
{

    public function store($task_id, StoreOfferRequest $request)
    {
        $task = UserTasks::find($task_id);
        if ($task && TaskOffers::store($task, $request->all())) {
            return response()->json(['success' => true]);
        }
        fail_message('Невозможно создать предложение');
    }

}

app/Http/Controllers/API/Tasks/ReportsController.php
<?php

namespace App\Http\Controllers\API\Tasks;

use App\Http\Controllers\Controller;
use App\UserTaskReports;
use App\Http\Requests\CreateTaskReportsRequest;
use App\Http\Requests\UpdateTaskReportsRequest;
use App\UserTasks;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use App\User;


class ReportsController extends Controller
{
    /**
     * Store a newly created taskreports in storage.
     *
     * @param UserTasks $task
     * @param Request $request
     * @return JsonResponse
     */
    public function store(UserTasks $task, Request $request)
    {
        $request->request->set('user_id', \user()->id);
        $task->reports()->create($request->all());
        return response()->json(['success' => true]);
    }
}

app/Http/Controllers/API/Tasks/ReviewsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Uer
 * Date: 26.03.2018
 * Time: 16:30
 */

namespace App\Http\Controllers\API\Tasks;


use App\Decorators\Tasks\ReviewDecorator;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Tasks\StoreReviewRequest;
use App\Http\Resources\APICollection;
use App\Http\Resources\Profile\UserReviewsResource;
use App\Review;
use App\User;
use App\UserTasks;
use Illuminate\Http\Request;

class ReviewsController extends Controller
{

    public function store($task_id, StoreReviewRequest $request)
    {
        $task = UserTasks::find($task_id);
        if ($task && Review::store($task, $request->all())) {
            return response()->json(['success' => true]);
        }
        error('Невозможно создать отзыв');
    }

    public function update($task_id, $review_id, StoreReviewRequest $request)
    {
        $task = UserTasks::find($task_id);
        $review = Review::find($review_id);
        if ($task && $review && $review->edit($task, $request->all())) {
            return response()->json(['success' => true]);
        }
        error('Невозможно редактировать отзыв');
    }

    public function index(User $user, Request $request)
    {
        $reviews = Review::getListForUser($user->id, $request->positive);
        return new APICollection($reviews, UserReviewsResource::class);
    }

}

app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Notifications\ApproveTask;
use App\Notifications\DeleteTask;
use App\Notifications\UnApproveTask;
use App\UserTasks;
use Illuminate\Support\Facades\Mail;
use Redirect;
use Schema;
use App\UserTaskReports;
use App\Http\Requests\CreateTaskReportsRequest;
use App\Http\Requests\UpdateTaskReportsRequest;
use Illuminate\Http\Request;

use App\User;
use App\Category;


class TaskController extends Controller
{

    /**
     * Display a listing of taskreports
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $taskCollection = UserTasks::orderByDesc('id')->get();

        return view('admin.task.index', compact('taskCollection'));
    }

    /**
     * @param UserTasks $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function approve(UserTasks $task)
    {
        $task->status = UserTasks::STATUS_OPENED;
        $task->save();
        $task->creator->notify(new ApproveTask($task));
        if ($task->creator && $task->creator->email)
            Mail::send(new \App\Mail\ApproveTask($task));
        return back();
    }

    /**
     * @param UserTasks $task
     * @return \Illuminate\Http\RedirectResponse
     */
    public function unapprove(UserTasks $task)
    {
        $task->status = UserTasks::STATUS_MODERATE;
        $task->save();
        $task->creator->notify(new UnApproveTask($task));
        if ($task->creator && $task->creator->email)
            Mail::send(new \App\Mail\UnApproveTask($task));
        return back();
    }

    public function delete(UserTasks $task)
    {
        $task->delete();
        $task->creator->notify(new DeleteTask($task));
        if ($task->creator && $task->creator->email)
            Mail::send(new \App\Mail\DeleteTask($task));
        return back();
    }




}

app/Http/Controllers/Tasks/ReviewsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Uer
 * Date: 26.03.2018
 * Time: 16:30
 */

namespace App\Http\Controllers\Tasks;


use App\Http\Controllers\Controller;
use App\Http\Requests\Api\Tasks\StoreReviewRequest;
use App\Http\Resources\APICollection;
use App\Http\Resources\Profile\UserReviewsResource;
use App\Review;
use App\User;
use App\UserTasks;
use Illuminate\Http\Request;

class ReviewsController extends Controller
{

    public function store($task_id, StoreReviewRequest $request)
    {
        $task = UserTasks::find($task_id);
        //dd($task);
        if ($task && Review::store($task, $request->all())) {
            return redirect()->back();
        }
        return redirect()->back()->withErrors('Невозможно создать отзыв');
    }

    public function update($task_id, $review_id, StoreReviewRequest $request)
    {
        $task = UserTasks::find($task_id);
        $review = Review::find($review_id);
        if ($task && $review && $review->edit($task, $request->all())) {
            return response()->json(['success' => true]);
        }
        error('Невозможно редактировать отзыв');
    }

    public function index(User $user, Request $request)
    {
        $reviews = Review::getListForUser($user->id, $request->positive);
        return new APICollection($reviews, UserReviewsResource::class);
    }

}

resources/views/admin/task/arbitration.blade.php
@extends('admin.layouts.master')

@section('content')

    @if ($taskCollection->count())
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">Задания</div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-hover table-responsive datatable" id="datatable">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название</th>
                        <th>Пользователь</th>
                        <th>Статус</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($taskCollection as $row)
                        <tr>
                            <td>{{$row->id }}</td>
                            <td><a href="{{route('task.review', ['userTasks' => $row])}}">{{ $row->name }}</a></td>
                            <td>
                                <a href="{{route('profile_show', ['id' => $row->creator->id])}}">{{ $row->creator->profile->name }}</a>
                            </td>
                            <td>{{ $row->status }}</td>
                            <td>
                                <a href="{{route('admin.tasks.arbitration.confirm', ['id' => $row->id])}}"
                                   class="btn btn-xs btn-success">Подтвердить сделку</a>
                                <a href="{{route('admin.tasks.arbitration.cancel', ['id' => $row->id])}}"
                                   class="btn btn-xs btn-danger">Отменить сделку</a>
                                <a href="{{route('admin.tasks.arbitration.review', ['id' => $row->id])}}"
                                   class="btn btn-xs btn-info">Просмотр</a>
                                <a href="{{route('task.review', ['userTasks' => $row])}}"
                                   class="btn btn-xs btn-info">Перейти к заданию</a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    @else
        {{ trans('quickadmin::templates.templates-view_index-no_entries_found') }}
    @endif

@endsection

<script>
    document.addEventListener('DOMContentLoaded', function () {
        let table = $('#datatable').DataTable();

        table.order([0, 'desc']).draw();
    });
</script>

resources/views/admin/task/index.blade.php
@extends('admin.layouts.master')

@section('content')

    @if ($taskCollection->count())
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">Задания</div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-hover table-responsive datatable" id="datatable">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Название</th>
                        <th>Пользователь</th>
                        <th>Статус</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($taskCollection as $row)
                        <tr>
                            <td>{{$row->id }}</td>
                            <td><a href="{{route('task.review', ['userTasks' => $row])}}">{{ $row->name }}</a></td>
                            <td>
                                @if($row->creator && $row->creator->profile)<a
                                        href="{{route('profile_show', ['id' => $row->creator->id])}}">{{ $row->creator->profile->name }}</a>@endif
                            </td>
                            <td>{{ $row->status }}</td>
                            <td>
                                @if($row->getOriginal('status') == \App\UserTasks::STATUS_MODERATE)
                                    <a href="{{route('admin.tasks.approve', ['task' => $row])}}"
                                       class="btn btn-xs btn-success">Подтвердить</a>
                                @elseif($row->getOriginal('status') == \App\UserTasks::STATUS_OPENED)
                                    <a href="{{route('admin.tasks.unapprove', ['task' => $row])}}"
                                       class="btn btn-xs btn-danger">Отклонить</a>
                                @else
                                    <a href="#" disabled class="btn btn-xs btn-success">Подтвердить</a>
                                @endif
                                <a href="{{route('task.review', ['userTasks' => $row])}}"
                                   class="btn btn-xs btn-info">Перейти к заданию</a>
                                <a href="{{route('admin.tasks.delete', ['task' => $row])}}"
                                   onclick="return confirm('Вы действительно хотите удалить задание?');"
                                   class="btn btn-xs btn-danger">Удалить</a>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    @else
        {{ trans('quickadmin::templates.templates-view_index-no_entries_found') }}
    @endif

@endsection

<script>
    document.addEventListener('DOMContentLoaded', function () {
        let table = $('#datatable').DataTable();
        table.order([0, 'desc']).draw();
    });
</script>