routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


/**
 * Route for UI
 * TODO Delete if it becomes unnecessary
 */
Route::get('ui', function () {
    return (new \App\Helpers\SVGViewer\SvgViewer('s/images/useful/svg/theme/symbol-defs.svg'))->rengerSvg();
});

Route::get('lara-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

Route::get('hack-test', function () {
    //$task = \App\UserTasks::find(469);

//    $deal = new \App\Services\WalletOneSafeDeal\WOSafeDeal();
////        $data = $deal::deal()->confirmDeal($task->deal->id);;
//
//    $data = $deal::payer()->getPayerRefunds($task->creator_id);
////    $data = $deal::deal()->cancelDeal($task->deal->id);;
////    $data = $deal::beneficiary()->getBeneficiaryPayouts($task->executor_id);
////    $data = $deal::deal()->completeDeal($task->deal->id);
//    dd($data);

    /*$task->update([
        'executor_id' => 0,
        'status' => 1,
        'executor_card_id' => null
    ]);
    \App\Review::whereTaskId($task->id)->forceDelete();
    \App\UserTaskDeal::query()->delete();*/

    dd("А хрен там! =)");


//    \App\User::find($task->creator_id)->notify(new \App\Notifications\PaymentStatusChanged($task, false));
});

//Route::get('test', function () {
////    $task = \App\UserTasks::find(request('task_id'));
//    $base_url = 'https://maps.googleapis.com/maps/api/geocode/json?';
//    $params = '&language=en&result_type=administrative_area_level_1';
//    $client = new \GuzzleHttp\Client();
////    $lat = $task->data['address'][0]['lat'] ?? false;
////    $lon = $task->data['address'][0]['lon'] ?? false;
//    $lat = '55.755826';
//    $lon = '37.617300';
//    if ($lat && $lon) {
//        $full_url = $base_url . 'latlng=' . $lat . ',' . $lon . '&key=' . config('services.google.maps_api_key').$params;
////        dd($full_url);
//        try {
//            $result =  json_decode_try($client->get($full_url)->getBody()->getContents());
//            $city = $result['results'][0]['address_components'][0]['long_name'];
//            if (strpos($city,' Oblast')) {
//                $city = stristr($city, ' Oblast', true);
//            }
//        }catch (Exception $e){
//            $city = \App\City::first()->name;
//        }
//    }
//    dd($city);
//    return '';
//    $safeDeal = new App\Services\WalletOneSafeDeal\WOSafeDeal();
//    return $safeDeal::deal()->getDeal('59113ed6-a95d-4e9b-a742-5c2ca20cad2f');
//    return $safeDeal::web()->payDeal([
//        "PlatformDealId" => 'c7769d6e-5233-11e8-9c2d-fa7ae01bbebc', // Идентификатор сделки на стороне площадки
//        "ReturnUrl" => 'http://pom.laraman.ru/payments', // Урл возврата пользователя
//    ]);
//});

Route::post('payments', 'Payment\SBRController@handleWalletOneRequest');


//Route::get('/', 'HomeController@index')->name('home');

Route::post('pay/in_request', 'Payment\ProcessorController@in_request')->name('in_request');

Route::group(['middleware' => ['web']], function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/home', 'HomeController@index');

    Auth::routes();

    Route::post('/finish-register/prevalidate', 'Auth\RegisterController@ajaxValidate')->name('register_prevalidate');

    /*
     * Tasks group
     * */
    Route::group(['as' => 'task.', 'prefix' => 'task', 'namespace' => 'Tasks'], function () {
        Route::group(['middleware' => 'auth'], function () {
            Route::get('list', 'ListController@index')->name('list');
            Route::post('report/{id}', 'PreviewController@report')->name('report');
            Route::post('comment/{userTasks}', 'PreviewController@comment')->name('comment');
            Route::get('edit/{category}/{subcategory}/{userTasks}', 'EditController@index')->name('edit');
            Route::post('edit/{category}/{subcategory}/{userTasks}', 'EditController@edit')->name('edit');
            Route::post('field_edit/{userTasks}/{field}', 'EditController@field_edit')->name('edit.field');
            Route::post('/{task}/executor', 'EditController@selectExecutor')->name('edit.select-executor');
        });
        Route::post('store', 'NewController@storeOldData')->name('store.old');
        Route::get('all', 'ListController@all')->name('all');
        Route::get('sort', 'ListController@sort')->name('sort');
        Route::get('preview/{userTasks}', 'PreviewController@index')->name('review');

        Route::post('/{task}/review', 'ReviewsController@store')->name('review.store');
        Route::post('/{task}/offers', 'OffersController@store')->name('offers.store');
        Route::post('/offers/{offer}', 'OffersController@update')->name('offers.update');
        Route::delete('/offers/{offer}', 'OffersController@remove')->name('offers.remove');
        Route::get('/{task}/offers', 'PreviewController@getTaskReviews')->name('offers.sort');
        Route::get('new/{category}/{subcategory?}', 'NewController@index')->name('new');
        Route::get('copy/{userTasks}', 'NewController@copy_new')->name('copy');
        Route::post('create/{category}/{subcategory}', 'NewController@create')->name('create');
        Route::post('search', 'NewController@search')->name('search');
    });

    /*
     * Payment grout
     */

    Route::group(['as' => 'payment.', 'prefix' => 'payment', 'namespace' => 'Payment', 'middleware' => 'auth'], function () {
        Route::post('pay', 'ProcessorController@pay')->name('pay');
        Route::get('in/{hash}', 'ProcessorController@in')->name('in');
        Route::get('test', 'ProcessorController@test')->name('test');
        Route::get('cancel', 'ProcessorController@cancel')->name('cancel');
        Route::group(['as' => 'sbr.', 'prefix' => 'sbr'], function () {
            Route::get('index', 'SBRController@index')->name('index');
            Route::get('bind-payer-card', 'SBRController@bindPayerCard')->name('bind-payer-card');
            Route::match(['get', 'post'], 'handle-bind-payer-card', 'SBRController@handleBindPayerCard')->name('handle-bind-payer-card');
            Route::get('bind-beneficiary-card', 'SBRController@bindBeneficiaryCard')->name('bind-beneficiary-card');
            Route::match(['get', 'post'], 'handle-bind-beneficiary-card', 'SBRController@handleBindBeneficiaryCard')->name('handle-bind-beneficiary-card');
            Route::post('pay/{task}', 'SBRController@pay')->name('pay');
            Route::match(['get', 'post'], 'handle-pay', 'SBRController@handlePay')->name('handle-pay');
        });
    });

    Route::group(['as' => 'executors.', 'prefix' => 'executors'], function () {
        Route::get('/', 'ExecutorsController@index')->name('index');
        Route::get('/sort', 'ExecutorsController@sort')->name('sort');
        Route::post('/offer-job', 'ExecutorsController@offerJob')->name('offer-job');
    });

    Route::group(['prefix' => 'templates'], function () {
        Route::get('/list', 'API\TemplateController@index');
        Route::post('/store', 'API\TemplateController@store');
        Route::put('/{template}', 'API\TemplateController@update');
        Route::delete('/{template}', 'API\TemplateController@destroy');
    });

    Route::group(['prefix' => 'profile'], function () {
        Route::get('/{user}', 'ProfileController@show')->name('profile_show')->where('user', '[0-9]+');;
    });

    /*
     * Get Register user email (modal register)
     */
//    Route::middleware(['guest'])->group(function () {

    Route::post('/get/email/register', 'Auth\RegisterController@getEmail')->name('get_email');

    /*
    * Google
    */
    Route::get('/google/login', 'Auth\SocialLoginContoller@redirectToGoogleProvider')->name('social_google_auth');
    Route::get('/google/callback', 'Auth\SocialLoginContoller@handleGoogleProviderCallback')->name('social_google_callback');

    /*
     * Facebook
     */
    Route::get('/facebook/login', 'Auth\SocialLoginContoller@redirectToFacebookProvider')->name('social_facebook_auth');
    Route::get('/facebook/callback', 'Auth\SocialLoginContoller@handleFacebookProviderCallback')->name('social_facebook_callback');

    /*
     * Vkontakte
     */
    Route::get('/vk/login', 'Auth\SocialLoginContoller@redirectToVkProvider')->name('social_vk_auth');
    Route::get('/vk/callback', 'Auth\SocialLoginContoller@handleVkProviderCallback')->name('social_vk_callback');

    /*
     * Mail ru
     */
    Route::get('/mailru/login', 'Auth\SocialLoginContoller@redirectToMailProvider')->name('social_mailru_auth');
    Route::get('/mailru/callback', 'Auth\SocialLoginContoller@handleMailProviderCallback')->name('social_mailru_callback');
//    });

    /*
     * Congratulation
     */
    Route::get('/email/congratulation', 'Auth\RegisterController@congratulation')->name('congratulation');

    /*
     * Verification email
     */

    Route::get('/email/verification/{token}/{email}', 'Auth\RegisterController@checkToken')->name('email_verified');

    /*
     * Step 2 email register (After modal)
     */

    Route::get('/finish/registration', 'Auth\RegisterController@endRegister')->name('finish_register');

    Route::get('/finish/social/registration', 'Auth\SocialLoginContoller@endRegisterSocial')->name('finish_register_social');

    /*
     * Save data (step 2)
     */
    Route::post('create', 'ProfileController@postCreateProfile')->name('profile_create');


    /*
     * ????
     */
    Route::get('pick-email', 'Auth\LoginController@pickeEmail');
    Route::post('handle-email', 'Auth\LoginController@handleEmail');

    /*
     * Get JSON City
     */
    Route::group(['prefix' => 'location'], function () {

resources/views/pages/congratulation.blade.php
@extends('layouts.main')
@section('title') Подтверждение email @stop
@section('content')
    <div class="container">
        <div class="confirm-container text-center " style="margin-top: 50px">
            <h3>Вы успешно подтвердили email</h3>
        </div>
    </div>
@stop

resources/views/pages/contacts.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-contacts">
                            {!! $page->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/faq.blade.php
@extends('layouts.basic')

@section('title')Отзывы исполнителей @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-tech-content">
                            <div class="l-faq">
                                <h1>Частые вопросы</h1>
                                <div id="faq" class="l-faq__dropdowns">
                                    @foreach($collection as $key => $item)
                                        <div @if($key > 9) hidden @endif onload="getActive({{$item->slug}})"
                                             id="{{$item->slug}}"
                                             class="l-faq__dropdowns-item">
                                            <button data-toggle="collapse" data-target="#faq_{{$key}} "
                                                    class="l-faq__dropdowns-item-btn">
                                                <svg width="1em" height="1em" class="icon icon-quote">
                                                    <use xlink:href="s/images/useful/svg/theme/symbol-defs.svg#icon-quote"></use>
                                                </svg>
                                                <span>{{$item->question}}</span>
                                            </button>
                                            <div id="faq_{{$key}}" class="l-faq__dropdowns-item-content-wrp collapse">
                                                <div class="l-faq__dropdowns-item-content">
                                                    {!! $item->answer !!}
                                                </div>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>

                                @if(count($collection) >9)
                                    <div id="show-more" class="l-faq__btn"><span style="cursor:pointer;"
                                                                                 class="but but_bondi"><span>Показать еще</span></span>
                                    </div>
                                @endif

                                <div id="hide-more" hidden class="l-faq__btn"><span style="cursor:pointer;"
                                                                                    class="but but_bondi"><span>Скрыть</span></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

    @push('scripts')
        <script>

            jQuery('#show-more').on('click', function () {
                jQuery('#faq .l-faq__dropdowns-item').show();
                jQuery('#show-more').hide();
                jQuery('#hide-more').show();
            });

            jQuery('#hide-more').on('click', function () {
                jQuery('#faq .l-faq__dropdowns-item').slice(10, jQuery('#faq .l-faq__dropdowns-item').length).hide();
                jQuery('#hide-more').hide();
                jQuery('#show-more').show();
            });

            jQuery('#faq .l-faq__dropdowns-item').each(function (i, element) {
                if (window.location.hash === '#' + element.id) {
                    jQuery(this).find('.l-faq__dropdowns-item-btn').addClass('active');
                    jQuery(this).find('.l-faq__dropdowns-item-content-wrp').addClass('in');
                }
            })
        </script>
    @endpush

@endsection

resources/views/pages/how-it-works.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>

    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        {!! $page->content !!}
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/how-performer.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')


    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-how-perfomer">
                            {!! $page->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/mass-media.blade.php
@extends('layouts.basic')

@section('title')СМИ о нас @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-mass-media" id="safe-and-guarantees">
                            @foreach($collection as $post)
                                <div class="l-mass-media__item">
                                    <div class="l-mass-media__item-head">
                                        <div class="date">{{$post->date}}</div>
                                        <div class="title"><span>{{$post->source}}</span> / {{$post->title}}</div>
                                    </div>
                                    <p>{{$post->content}}</p>
                                    <div class="h-object-fit"><img src="{{url('uploads/'.$post->img)}}" alt=""/></div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/no-risk.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        {!! $page->content !!}
        <div class="l-no-risk-faq">
            <div class="container">
                <h6>Частые вопросы</h6>
                @foreach($questions as $key => $question)
                    <div class="l-faq__dropdowns-item">
                        <button data-toggle="collapse" data-target="#faq_{{$key}}"
                                class="l-faq__dropdowns-item-btn clearfix">
                            <svg width="1em" height="1em" class="icon icon-quote ">
                                <use xlink:href="s/images/useful/svg/theme/symbol-defs.svg#icon-quote"></use>
                            </svg>
                            <span>{{$question->question}}</span>
                        </button>
                        <div id="faq_{{$key}}" class="l-faq__dropdowns-item-content-wrp collapse">
                            <div class="l-faq__dropdowns-item-content">
                                {!! $question->answer !!}<a href="{{url('faq')}}">Подробнее</a>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/performers-reviews.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-cust-rev l-perf-rev">
                            <h1>Отзывы исполнителей о Pomogoo</h1>
                            <div class="l-cust-rev__annotation">
                                {!! $page->content !!}
                            </div>
                            <div class="l-cust-rev__content">
                                @foreach($reviews as $review)
                                    @if(!$review->user) @continue @endif
                                    <div class="l-cust-rev__item clearfix">
                                        <div class="l-cust-rev__item-img h-object-fit"><img
                                                    src="{{$review->user->profile->avatar_thumb}}" alt=""/></div>
                                        <div class="l-cust-rev__item-txt">
                                            <div class="l-cust-rev__item-txt-wrp clearfix">
                                                <div class="l-cust-rev__item-user"><span
                                                            class="l-cust-rev__item-user-name"><a
                                                                href="{{url('profile', ['id' => $review->user->id])}}">{{$review->user->name}}</a></span>
                                                </div>
                                                <div class="l-cust-rev__item-done"><span
                                                            class="l-cust-rev__item-done-txt">Количество выполненых заданий: {{$review->user->getTaskCount()}}
                                                        . Средняя оценка: {{$review->user->avg_mark['total']}}</span><span
                                                            class="l-cust-rev__item-done-stars">
                                                        @for($i = 0; $i < $review->user->avg_mark['total']; $i++)
                                                            <svg width="1em" height="1em" class="icon icon-star ">
                              <use xlink:href="s/images/useful/svg/theme/symbol-defs.svg#icon-star"></use>
                            </svg>
                                                        @endfor
                                                    </span></div>
                                                <div class="l-cust-rev__item-rev">
                                                    {!! $review->text !!}
                                                </div>
                                                <div class="l-cust-rev__item-caption"><a href="{{$review->source}}">Источник</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                            <div class="l-cust-rev__btns">
                                <a href="{{url('/task-categories')}}" class="but but_bondi but_bondi_lg">
                                    <span>Создать задание</span>
                                </a>
                                <a href="{{url('/how-performer')}}" class="c-check-link">
                                    <span>Может быть вы хотите стать исполнителем Pomogoo?</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/receipt.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    <div class="col-md-9">
                        <div class="l-service-rules">
                            {!! $page->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/rewards.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-rewards">
                            {!! $page->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/rules.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-service-rules">
                            {!! $page->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/security.blade.php
@extends('layouts.basic')

@section('title'){{$page->title}} @endsection
@section('body')

    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="row row_no-pad">
                    @widget('Pages')
                    <div class="col-md-9">
                        <div class="l-security" id="safe-and-guarantees">
                            {!! $page->content !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection

resources/views/pages/task_category.blade.php
@extends('layouts.basic')

@section('title')Категории заданий @endsection
@section('body')
    <div id="fb-root"></div>
    <div class="l-page-wrapper">
        @widget('MainMenu')
        <div class="l-tech-wrapper">
            <div class="container">
                <div class="categoria_zadanija">
                    <div class="categoria_zadanija_header">
                        <h2>Выберите категорию задания</h2>
                    </div>
                    <div class="categoria_zadanija_content_wrap">
                        @foreach($cat_tree as $category)
                            <div class="categoria_zadanija_content">
                                <div class="categoria_zadanija_content_ico"></div>
                                <div class="categoria_zadanija_content_list">
                                    <ul class="h-list">
                                        <li>
                                            <a href="{{route('task.new', [
                                            'category' => $category->slug,
                                            'subcategory' => $defaultSlug,
                                            'select' => true
                                            ])}}">
                                                {{$category->name}}
                                            </a>
                                            <span>
                                                <svg width="1em" height="1em" class="icon {{$category->icon}} ">
                                                    <use xlink:href="s/images/useful/svg/theme/symbol-defs.svg#{{$category->icon}}"></use>
                                                </svg>
                                            </span>
                                        </li>
                                        @if($category->subcategories)
                                            @foreach($category->subcategories as $subcategory)
                                                <li>
                                                    <a href="{{route('task.new', [
                                                    'category' => $category->slug,
                                                    'subcategory' => $subcategory->slug,
                                                    'select' => true
                                                    ])}}">
                                                        {{$subcategory->name}}
                                                    </a>
                                                </li>
                                            @endforeach
                                        @endif
                                    </ul>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
        @widget('Footer')
    </div>

@endsection